# Generated by Django 4.2.2 on 2023-07-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='img',
            new_name='image',
        ),
    ]
